package server

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestHandleOpenAPISpec(t *testing.T) {
	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/api/v1/openapi.json", nil)
	handleOpenAPISpec(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want 200", rec.Code)
	}
	if ct := rec.Header().Get("Content-Type"); ct != "application/json" {
		t.Errorf("Content-Type = %q, want application/json", ct)
	}
	var doc map[string]any
	if err := json.Unmarshal(rec.Body.Bytes(), &doc); err != nil {
		t.Fatalf("response is not valid JSON: %v", err)
	}
	// Spec is Swagger 2.0 (generated by swaggo/swag); verify the version key is present.
	swaggerVer, _ := doc["swagger"].(string)
	if swaggerVer == "" {
		t.Errorf("expected swagger version string, got: %v", doc["swagger"])
	}
	if doc["info"] == nil {
		t.Error("response missing 'info' field")
	}
	if doc["paths"] == nil {
		t.Error("response missing 'paths' field")
	}
}
