{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mantle.fullname" . }}
  labels:
    {{- include "mantle.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mantle.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      {{- if .Values.serviceMonitor.bearerTokenSecret }}
      bearerTokenSecret:
        name: {{ .Values.serviceMonitor.bearerTokenSecret.name }}
        key: {{ .Values.serviceMonitor.bearerTokenSecret.key }}
      {{- end }}
{{- end }}
