{{- if or (and .Values.database.url (not .Values.database.existingSecret)) (and .Values.encryption.key (not .Values.encryption.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mantle.fullname" . }}
  labels:
    {{- include "mantle.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.database.url (not .Values.database.existingSecret) }}
  database-url: {{ .Values.database.url | b64enc | quote }}
  {{- end }}
  {{- if and .Values.encryption.key (not .Values.encryption.existingSecret) }}
  encryption-key: {{ .Values.encryption.key | b64enc | quote }}
  {{- end }}
{{- end }}
